######################################################################
# Automatically generated by qmake (3.0) po 5 11 22:24:15 2015
######################################################################

TEMPLATE = app
TARGET = labyrinth2015-2
INCLUDEPATH += .

# Input
#HEADERS += #../client/client.h ../shared/components.h ../shared/tools.h
SOURCES += main.cpp # ../client/client.cpp ../shared/components.cpp ../shared/tools.cpp

QT += widgets