######################################################################
# Automatically generated by qmake (3.0) po 5 11 20:45:51 2015
######################################################################

TEMPLATE = app
TARGET = labyrinth2015
INCLUDEPATH += .

# Input
SOURCES += main.cpp

QT += widgets